name: Build

on:
  pull_request:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            name: windows
            task: packageReleaseMsi
            artifact: windows-msi
            path: ./composeApp/build/compose/binaries/main-release/msi/*.msi

          - os: ubuntu-latest
            name: linux
            task: packageReleaseAppImage
            artifact: linux-appimage
            path: ./PadConnectReceiver-x86_64.AppImage

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew ${{ matrix.task }}
          

      - name: Bundle AppImage
        if: matrix.name == 'linux'
        run: |
          APP_DIR="./composeApp/build/compose/binaries/main-release/app/PadConnectReceiver"
          
          ln -s ./bin/PadConnectReceiver "$APP_DIR/AppRun"
          
          cat <<EOF > "$APP_DIR/padconnectreceiver.desktop"
          [Desktop Entry]
          Type=Application
          Name=PadConnectReceiver
          Exec=AppRun
          Icon=padconnectreceiver
          Categories=Utility;
          EOF
          
          cp "$APP_DIR/lib/PadConnectReceiver.png" "$APP_DIR/padconnectreceiver.png" || touch "$APP_DIR/padconnectreceiver.png"
          wget -q https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          export APPIMAGE_EXTRACT_AND_RUN=1
          
          ./appimagetool-x86_64.AppImage "$APP_DIR" PadConnectReceiver-x86_64.AppImage

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.path }}