name: Build

on:
  pull_request:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            name: windows
            task: packageReleaseMsi
            artifact: windows-msi
            path: ./composeApp/build/compose/binaries/main-release/msi/*.msi

          - os: ubuntu-latest
            name: linux-x64
            task: packageReleaseAppImage
            artifact: linux-appimage-x64
            path: ./PadConnectReceiver-x86_64.AppImage

          - os: ubuntu-24.04-arm
            name: linux-arm64
            task: packageReleaseAppImage
            artifact: linux-appimage-arm64
            path: ./PadConnectReceiver-aarch64.AppImage

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 22 

      - name: Set up gradle caches
        uses: actions/cache@v5
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-padconnectreceiver-${{ hashFiles(
           '**/*.gradle',
           '**/*.gradle.kts',
           '**/gradle-wrapper.properties',
           '**/gradle.properties',
           '**/settings.gradle',
           '**/settings.gradle.kts',
           '**/libs.versions.toml'
           ) }}
          restore-keys: |
            ${{ runner.os }}-padconnectreceiver-

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew ${{ matrix.task }}
          

      - name: Bundle AppImage
        if: startsWith(matrix.name, 'linux')
        run: |
          APP_DIR="./composeApp/build/compose/binaries/main-release/app/PadConnectReceiver"
          
          ln -s ./bin/PadConnectReceiver "$APP_DIR/AppRun"
          
          cat <<EOF > "$APP_DIR/padconnectreceiver.desktop"
          [Desktop Entry]
          Type=Application
          Name=PadConnectReceiver
          Exec=AppRun
          Icon=padconnectreceiver
          Categories=Utility;
          EOF
          
          cp "$APP_DIR/lib/PadConnectReceiver.png" "$APP_DIR/padconnectreceiver.png" || touch "$APP_DIR/padconnectreceiver.png"

          ARCH=$(uname -m)

          if [ "$ARCH" = "aarch64" ]; then
            TOOL="appimagetool-aarch64.AppImage"
            OUTPUT="PadConnectReceiver-aarch64.AppImage"
          else
            TOOL="appimagetool-x86_64.AppImage"
            OUTPUT="PadConnectReceiver-x86_64.AppImage"
          fi
          
          wget -q "https://github.com/AppImage/appimagetool/releases/download/continuous/$TOOL"
          chmod +x "$TOOL"
          export APPIMAGE_EXTRACT_AND_RUN=1
          
          ./"$TOOL" "$APP_DIR" "$OUTPUT"

      - name: Stop Gradle Daemon
        if: startsWith(matrix.name, 'windows')
        run: ./gradlew --stop

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.path }}
