name: Build

on:
  pull_request:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            name: windows
            task: packageReleaseMsi
            artifact: windows-msi
            path: ./composeApp/build/compose/binaries/main-release/msi/*.msi

          - os: ubuntu-latest
            name: linux
            task: packageReleaseAppImage
            artifact: linux-appimage
            path: ./composeApp/build/compose/binaries/main-release/app/*.AppImage

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Linux dependencies
        if: matrix.name == 'linux'
        run: |
          sudo apt update
          sudo apt install -y fakeroot fuse libfuse2

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew ${{ matrix.task }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.path }}